### ISSUE TITLE
Not able to run after cloning

### ISSUE THREAD

**Issue by cashmash** [Antondomashnev/ADFBRequestDialogViewController#1]
Not able to run after cloning:
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by Antondomashnev** [comment]
Hi cashmash,

I've added Podfile. After cloning you should run 'pod install' and 'pod update'.

**Comment by cashmash** [comment]
thx
