### ISSUE TITLE
JRSwizzle ?

### ISSUE THREAD

**Issue by SebastianBO** [Antondomashnev/ADFBRequestDialogViewController#2]
/_-------Frameworks-------_/
# import <JRSwizzle/JRSwizzle.h>
# import <objc/runtime.h>

In your ADFBRequestDialobViewController, so how should i be able to drag them to the project? Remove  ? Did not think people swizzled still in Obj-C.. ;)

**/
pragma clang diagnostic ignored "-Wundeclared-selector"
    class_addMethod(FBDialogClass, @selector(FBDialog_swizzled_drawRect:), (IMP)FBDialog_swizzled_drawRect, "@:{CGRect={CGPoint=ff}{CGSize=ff}}");
    class_addMethod(FBDialogClass, @selector(FBDialog_swizzled_showWebView), (IMP)FBDialog_swizzled_showWebView, "@:");
    class_addMethod(FBDialogClass, @selector(FBDialog_swizzled_dismiss:), (IMP)FBDialog_swizzled_dismiss, "@:b");

```
NSError *error = nil;
if(![FBDialogClass jr_swizzleMethod:@selector(drawRect:) withMethod:@selector(FBDialog_swizzled_drawRect:) error:&error]){
    NSLog(@"Warning: failed to swizzle drawRect: with FBDialog_swizzled_drawRect:. Error %@", [error localizedDescription]);
}
if(![FBDialogClass jr_swizzleMethod:@selector(showWebView) withMethod:@selector(FBDialog_swizzled_showWebView) error:&error]){
    NSLog(@"Warning: failed to swizzle showWebView with FBDialog_swizzled_showWebView. Error %@", [error localizedDescription]);
}
if(![FBDialogClass jr_swizzleMethod:@selector(dismiss:) withMethod:@selector(FBDialog_swizzled_dismiss:) error:&error]){
    NSLog(@"Warning: failed to swizzle dismiss: with FBDialog_swizzled_dismiss:. Error %@", [error localizedDescription]);
}
```

**7

**Comment by Antondomashnev** [comment]
Hi SebastianBO,

Do you use cocoapods?
